apiVersion: v1
kind: Service
metadata:
  name: aceest-a
  namespace: aceest
spec:
  type: LoadBalancer
  selector:
    app: aceest-ab
    variant: a
  ports:
    - name: http
      port: 80
      targetPort: 8000
