apiVersion: v1
kind: Service
metadata:
  name: aceest-b
  namespace: aceest
spec:
  type: LoadBalancer
  selector:
    app: aceest-ab
    variant: b
  ports:
    - name: http
      port: 80
      targetPort: 8000
